### ISSUE TITLE
Remove libcloud reliance for S3 compatible backends

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-medusa#602]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=34251642)

As we're only using a small subset of Libcloud's features and it's currently limiting our ability to make Medusa faster and safer, we have decided to move away from it and implement async http operations for multipart uploads.

In that effort, we will be moving the S3 and S3 compatible storage classes to rely on https://github.com/aiokitchen/aiohttp-s3-client, which relies on aiohttp and implements concurrent uploads of chunks during multipart uploads. It also handles retries in case of failure of single chunk uploads for resiliency to network glitches.

This also allows us to remove:
- The reliance on the awscli (and its dependencies)
- The concurrent code that was built to upload multiple files at the same time

We will be able to lower the default multipart threshold to 20 MB for better performance (benchmarks should verify this number is appropriate as multipart uploads may have an overhead).

Implementing rate limiting of uploads is out of scope for this ticket.

## Definition of Done
- [ ] Libcloud is not used anymore in the S3 storage classes
- [ ] ~All features that were previously supported in the Libcloud implementation must be ported over to the new one~
  - [ ] ~KMS encryption support~ (Moved to #612)
  - [ ] ~Multiple authentication capabilities (instance profiles, access key/secret, ...)~ (#613)
- [ ] ~Chunk size must be adjusted based on the total file size to stay within the 10k chunks limit in S3~ (#614)
- [ ] We do not implement concurrency in Medusa's code anymore
- [ ] We don't rely on the awscli for large files uploads
- [ ] The size threshold for multipart uploads is lowered at 20MB by default (anything bigger than that gets uploaded concurrently).
